{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.clustersecretstore" -}}
{{- $files := .Files }}
{{- $default_values := .Values.clustersecretstore_defaults }}
{{- $global_values := .Values.global}}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .clustersecretstores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "helpers.renderGlobalIfExists" (dict "value" .name "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- if .controller }}
  controller: {{ .controller }}
  {{- end}}
  provider:
    {{- if .aws }}
    aws:
      service: SecretsManager
      region: {{ include "helpers.renderGlobalIfExists" (dict "value" (required "Region is required for cluster secret store" .aws.region) "global" $global_values) }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ required "Service account name is required for cluster secret store" .aws.auth.jwt.serviceAccountRef.name }}
            namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .aws.auth.jwt.serviceAccountRef.namespace "global" $global_values) }}
    {{- end }}
{{- end }}
{{- end }}