{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.serviceaccount" -}}
{{- $global_values := .Values.global}}
{{- $default_values := .Values.serviceaccount_defaults }}
{{- $common_defaults := .Values.common_defaults }}
{{- range .serviceaccounts }}
{{- if not .disabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default (include "common.names.fullname" $) }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}