{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.service" -}}
{{- $global_values := .Values.global}}
{{- $default_values := .Values.service_defaults }}
{{- $common_defaults := .Values.common_defaults }}
{{- range .services }}
{{- if not .disabled }}
---
{{- $type := .type | default "ClusterIP" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ required "Service has to inclue a name" .name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .name }}
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
    {{- if .selector }}
    {{- include "common.tplvalues.render" ( dict "value" .selector "context" $) | nindent 4 }}
    {{- end }}
  type: {{ $type }}
  {{- if .sessionAffinity }}
  sessionAffinity: {{ .sessionAffinity }}
  {{- end }}
  {{- if .sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if and .clusterIP (eq $type "ClusterIP") }}
  clusterIP: {{ .clusterIP }}
  {{- end }}
  {{- if (and (eq $type "LoadBalancer") (not (empty .loadBalancerIP))) }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  {{- if and (eq $type "LoadBalancer") .loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if or (eq $type "LoadBalancer") (eq $type "NodePort") }}
  externalTrafficPolicy: {{ .externalTrafficPolicy | quote }}
  {{- end }}
  ports: {{- include "common.tplvalues.render" (dict "value" .ports "context" $) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}