apiVersion: v2
name: chart-a
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: global-templates
    version: "*"
    repository: file://../../../../charts/global-templates
    import-values:
      - defaults